__ = "_"

[_____]
__ = "__ _ ____"
_ = ____________

[underscores]
_ = true
____ = [ ____, ___, _____ ]
_____ = [ ["_", "____"], [_.___] ]
___= { _ = 79.5, ___ = ___ }

[colon cases]

[____.__]
_ = "____"
__ = "1"
